# Generated by Django 5.0 on 2023-12-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
