# Generated by Django 5.0 on 2023-12-19 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_autos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auto',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
