# Generated by Django 5.0 on 2023-12-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_autorent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoRent',
        ),
    ]
