# Generated by Django 5.0 on 2023-12-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_autobooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoBooking',
        ),
    ]
