# Generated by Django 5.0 on 2023-12-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
