# Generated by Django 5.0 on 2023-12-25 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
