# Generated by Django 5.0 on 2023-12-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_paymentdetails_end_datetime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
