# Generated by Django 5.0 on 2023-12-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_paymentdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
