# Generated by Django 5.0 on 2023-12-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
