# Generated by Django 5.0 on 2023-12-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_paymentdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
