# Generated by Django 5.0 on 2023-12-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
