# Generated by Django 5.0 on 2023-12-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
