# Generated by Django 5.0 on 2024-01-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_paymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='status',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
