# Generated by Django 5.0 on 2024-01-02 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_auto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
