# Generated by Django 5.0 on 2024-01-02 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_auto_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auto',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
