# Generated by Django 5.0 on 2024-01-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_auto_date_added_alter_auto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='status',
            field=models.CharField(choices=[('In work, Available after some time', 'In work, Available after some time'), ('Available', 'Available')], max_length=100),
        ),
    ]
