# Generated by Django 5.0 on 2024-01-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_auto_date_added_alter_auto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
