# Generated by Django 5.0 on 2024-01-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_partner_contact_date_partner_contacted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='terms_conditions',
        ),
    ]
