# Generated by Django 5.0 on 2024-01-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
