# Generated by Django 5.0 on 2024-01-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
    ]
