# Generated by Django 5.0 on 2024-01-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_feedback_feedback_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_given',
        ),
    ]
