# Generated by Django 5.0 on 2024-01-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_feedback_feedback_given'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
