# Generated by Django 5.0 on 2024-01-06 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('change_of_plans', 'Change of Plans'), ('found_alternative', 'Found Alternative'), ('booking_mistake', 'Booking Mistake'), ('travel_restrictions', 'Travel Restrictions'), ('unforeseen_circumstances', 'Unforeseen Circumstances')], max_length=50)),
                ('password', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
