# Generated by Django 5.0 on 2024-01-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_cancellationreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationreason',
            name='password',
        ),
    ]
