# Generated by Django 5.0 on 2024-01-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_cancellationreason_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancellationReason',
        ),
    ]
