# Generated by Django 5.0 on 2024-01-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_cancellationreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationreason',
            name='payment',
        ),
    ]
