# Generated by Django 5.0 on 2024-01-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_delete_cancellationreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.paymentdetails')),
            ],
        ),
    ]
