# Generated by Django 5.0 on 2024-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_remove_cancellationreason_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
