# Generated by Django 5.0 on 2024-01-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_paymentdetails_is_canceled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancellationReason',
        ),
    ]
