# Generated by Django 5.0 on 2024-01-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_cancellationreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='initial_total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
