# Generated by Django 5.0 on 2024-01-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_paymentdetails_initial_total_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancellationReason',
        ),
    ]
