# Generated by Django 5.0 on 2024-01-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_cancellationreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationreason',
            name='original_total_cost',
        ),
        migrations.RemoveField(
            model_name='cancellationreason',
            name='remaining_cost',
        ),
    ]
