# Generated by Django 5.0 on 2024-01-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_remove_cancellationreason_original_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='initial_total_cost',
        ),
    ]
