# Generated by Django 5.0 on 2024-01-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_remove_paymentdetails_initial_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.paymentdetails')),
            ],
        ),
    ]
