# Generated by Django 5.0 on 2024-01-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_paymentdetailstraveller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetailsTraveller',
        ),
    ]
