# Generated by Django 5.0 on 2024-01-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_delete_paymentdetailstraveller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='vehicle_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='vehicle_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
