# Generated by Django 5.0 on 2024-01-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_alter_auto_vehicle_id_alter_traveller_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='vehicle_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='vehicle_id',
            field=models.CharField(max_length=20),
        ),
    ]
